#!/bin/zsh

vim Gemfile `find ./ -iname '*.rb' | grep -v vendor | grep -v eventmachine` `find ./ -iname '*.erb' | grep -v vendor | grep -v vendor | grep -v vendor | grep -v eventmachine` `find ./ -iname '*.yml' | grep -v vendor | grep -v eventmachine` `find ./ -iname '*.css' | grep -v eventmachine` `find ./ -iname '*.scss' | grep -v eventmachine` `find ./ -iname '*.js' | grep -v vendor | grep -v eventmachine` `find ./ -iname '*.rake' | grep -v vendor | grep -v eventmachine`
