development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: zackmartinsek
  :password: medo1234
  :enable_starttls_auto: true
test:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: zackmartinsek
  :password: medo1234
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: zackmartinsek
  :password: medo1234
  :enable_starttls_auto: true
